import {Dropdown} from '../interfaces/dropdown';
import {signal} from '@angular/core';

export class Global {
  public static isCollapsed= signal(false);
  public static currentUserType = signal<any>(null);
  public static shipmentEdited = signal(false);
  public static formattedMaxDate = signal<any>(null);
  public static formattedMaxDateTime = signal<any>(null);
  public static carrierFilterData = signal<Dropdown[]>([]);
  public static statusFilterData = signal<Dropdown[]>([]);
  public static clientFilterData = signal<Dropdown[]>([]);
  public static trackDelayRecCount = signal(0);
  public static trackDeliveryDateExceptionRecordCount = signal(0);
  public static trackPendingRecCount = signal(0);
  public static trackRequestForQuoteRecCount = signal(0);
  public static trackPrebookedNoteLateRecCount = signal(0);
  public static trackPrebookedRolledCount = signal(0);
  public static trackTruckAtPickupCount = signal(0);
  public static trackTruckAtDeliveryCount = signal(0);
  public static trackTruckDeliveredCount = signal(0);
  public static trackPrebookedAndLateRecCount = signal(0);
  public static trackLateQuoteResponsesRecCount = signal(0);
  public static trackSubmittedQuotesRecCount = signal(0);
  public static trackTruckloadInTransitRecCount = signal(0);
  public static trackPickupDateAndTimePassedRecCount = signal(0);
  public static trackAppointmentRequiredRecCount = signal(0);
  public static trackTruckloadProblemRecCount = signal(0);
  public static trackTruckloadFailureRecCount = signal(0);
  public static trackTruckloadDispatchedRecCount = signal(0);
  public static trackTruckloadAllRecCount = signal(0);
  public static trackMissingTransitUpdateRecCount = signal(0);
  public static trackLateDeliveryRecCount = signal(0);
  public static trackDeliveredNeedsPODRecCount = signal(0);
  public static noTrackRecordCount = signal(0);
  public static trackPriorityRecCount = signal(0);
  public static trackExpeditedRecCount = signal(0);
  public static trackSubmittedQuoteCount = signal(0);
  public static trackNotLateCount = signal(0);
  public static trackLatePickupsCount = signal(0);
  public static trackDeliveryTodayCount = signal(0);
  public static trackDeliveryOsdCount = signal(0);
  public static trackRequestQuoteCount = signal(0);
  public static trackTruckloadPendingRecCount = signal(0);
  public static noTrackReturns = signal(0);
  public static trackProblemCount = signal(0);
  public static recordStatus = signal('recordsSearch');
  public static recordsCompleteCount = signal(0);
  public static recordsPendingCount = signal(0);
  public static recordsIncompleteCount = signal(0);
  public static trackOceanCount = signal(0);
  public static trackWhiteboardCount = signal(0);
}
