export const environment = {
  production: true,
  cookie_domain: 'spa.apps.il2000.com',
  cookie_expiration: 7,
  cookie_secure: true,
  user_pool_id: 'us-east-1_2P8p6qrpR',
  app_client_id: '2gf9om58v411udi599jfvj12k7',
  ENV_NSYNC_BASE_URL: 'https://spansync.services.il2000.com/nsync',
  ENV_ICARUS_BASE_URL: 'https://icarus.apps.il2000.com/icarus',
  ENV_TIBER_BASE_URL: 'https://tiber.apps.il2000.com/Tiber',
  ENV_LAMBDA_API_BASE_URL: 'https://inutils.services.il2000.com/webservice',
  ENV_LAMBDA_TRACKING_API_BASE_URL : 'https://fr3tx7ufke.execute-api.us-east-1.amazonaws.com/prod',
  ENV_LAMBDA_TL_TRACKING_API_BASE_URL: 'https://dkk5q0fs5f.execute-api.us-east-1.amazonaws.com/Prod/tracking',
  ENV_LAMBDA_RECORDS_API_BASE_URL : 'https://2hpblratld.execute-api.us-east-1.amazonaws.com/prod', // use /prod for prod
  ENV_USER_CREDENTIAL_API_BASE_URL: 'https://iszhmizbta.execute-api.us-east-1.amazonaws.com/Prod',
  RATER_URL: 'https://spa.services.il2000.com/rates',
  API_TOKEN: 'ILToken MzEwYWM2MWI1ZTE1ZDlhZGY4NDEzNzVhMjU2MzcyYjYwZWE2YjRkMjg1NzVkNjU0', // TODO: Secure this upon switch to prod
  SHIPMENT_HISTORY_URL: 'https://xfydegjoo1.execute-api.us-east-1.amazonaws.com/Prod',
  REPORT_ANALYSIS_URL: 'https://y93zg7bd13.execute-api.us-east-1.amazonaws.com/Prod',
  CLIENT_FIELDS_URL: 'https://iwtix4gso0.execute-api.us-east-1.amazonaws.com/Prod',
  VOLUME_RATES_URL: 'https://n9ch3759pb.execute-api.us-east-1.amazonaws.com/Prod',
  MILEAGE_URL: 'https://spa.services.il2000.com/mileage',
  DAT_INTEGRATION_URL: 'https://outqx4xgg8.execute-api.us-east-1.amazonaws.com/Prod',
  CARRIER_PROFILING_URL: 'https://h4ltft9tvi.execute-api.us-east-1.amazonaws.com/Prod',
  NOTES_PROFILING_URL: 'https://0d3t5xa0vl.execute-api.us-east-1.amazonaws.com/Prod',
  LOAD_TRACK_URL: 'https://oo7wtzzg56.execute-api.us-east-1.amazonaws.com/Prod',
  AWS_CLAIM_URL: 'https://yqetqbxb31.execute-api.us-east-1.amazonaws.com/Prod',
  AWS_CLAIM_API_KEY: 'Bj6n9jl4jS5OZcGh3TFr4q97UyufDEK2fDD8T1v9',
  FAST_FOREX_URL: 'https://api.fastforex.io/',
  FAST_FOREX_API_KEY: 'c0ded72b24-ebbdb9361f-s6bznm',
  TRUCKER_TOOLS_API_ACTIVE: false,
  MACROPOINT_API_ACTIVE: true,
  DAT_API_ACTIVE: true,
  MACROPOINT_API_URL: 'https://52lzvlxma5.execute-api.us-east-1.amazonaws.com/Prod',
  CARRIER_SOURCE: 'MCLEOD'
};
